"""Module containing project constants."""

NUMBER_OF_CHAR = 20
MAX_LENGTH_CATEGORY_NAME = 20
MAX_LENGTH_USERNAME = 150
MAX_LENGTH_EMAIL = 254
MAX_LENGTH_TITLE = 256
MAX_LENGTH_SLUG = 50
MAX_LENGTH_ROLE = 50
VALID_CHARACTERS_USERNAME = r'^[\w.@+-]+'
ME_URL = 'me'
EMAIL_ADMIN = 'admin@yamdb.ru'
MIN_SCORE = 1
MAX_SCORE = 10
