# Generated by Django 3.2 on 2025-03-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_auto_20250323_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
